DataContext = {
    "base_report": "A parent foundation file will be received daily, reflecting updates on new hires and employee exits. This file serves as the source for the Employee Demographic Report, which includes details such as Assignment Status. Employees marked as “Active” represent the current live headcount of the organization at any given time.This report should be the primary reference for both employees and HR teams when accessing any employee-related information, including : Status of exited employees , Details of new joiners ,Reporting manager information , Gender , Date of Birth, Designation, Department, and Sub-Department",
    "offboarding_checklist": "When an employee resigns, the resignation is first approved by the respective manager and Regional HR. Once the resignation is accepted, the Offboarding Report automatically generates a dedicated row for that employee. Each resigned employee’s row includes 12 exit checklists, with the status of each checklist summarized. Additionally, detailed task information for every checklist is provided. For example, an exit checklist may contain 5 tasks or questions, and each question is documented along with its corresponding response.",
    "goal_setting_status": "The goal-setting process is initiated at the start of each financial year, which runs from April of the current year to March of the following year. Employees first discuss and define their goals. Once goals are set, they are submitted to the reporting manager for approval. After the manager’s approval, the reviewer provides the final confirmation. The status column in this report indicates the current stage of each goal: Pending with Employee: Goals have not yet been created or submitted by the employee , Pending with Manager: Goals have been submitted by the employee but are awaiting the manager’s approval , Pending with Reviewer: Goals have been approved by the manager and are awaiting final review. This report captures the status of the same in the column status ",
    "performance_goal_report_2025_2026": ". Once goals are approved, the goal name, goal description and goal weightage are enlisted in this report.",
    "pms_task_status_report_all": "Once the performance cycle begins, employees initiate a self-assessment of their assigned goals. They rate themselves on a scale of 1 (lowest) to 5 (highest). After completing the self-evaluation, the performance document is forwarded to the reporting manager for their review and evaluation. Following the manager’s assessment, the reviewer examines the ratings and either approves the document or returns it for necessary revisions. Once all approvals are completed, the document is marked as “Approved.”This report reflects the status of each performance document throughout the process. For certain employees, this evaluation cycle is conducted on a quarterly basis and for all employees it is avaialble for mid-year and annual. ",
    # "pms_q2_25_26_rating_report_all": "Once the ratings are approved as stated in the pms_task_status_report_all , the value of the ratings appear in this report for all the completed forms.",
    "pip_transaction_report": "Captures the ongoing Performance Improvement Plan cases for the current financial year. This report captures the document status, PIP start date , completion date etc.",
    "probation_confirmation": "",
    "performance_360_degree_feedback_participants_status_all": "This process starts in Q2 every year, where self manager and participant feedback is provided for each employee. Once the feedback is given the status gets updated to completed. The Status of each form is captured against each participant entry .",
    "leave_transaction_with_balance_report_leave_transaction_with_balance_report": "",
    "permormance_rating_report": "",
    "historical_ratings_and_other_information": "This captures last 3 years ratings, educational qualification and work experience .",
    "goal_detail_report": "This captures the Individual Development Details for all the employees who have submitted there development plan in the HRMS"
}